/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#2a2a2a',
        'inverse-on-surface': '#313030',
        'tertiary-container': '#b38778',
        'tertiary-fixed': '#ffdbd0',
        'inverse-surface': '#e5e2e1',
        'surface-container-lowest': '#0e0e0e',
        'secondary-fixed-dim': '#70d8c8',
        'outline': '#aa8980',
        'on-tertiary-fixed': '#2f140b',
        'on-primary-fixed': '#3b0900',
        'surface-dim': '#131313',
        'primary-fixed': '#ffdbd1',
        'on-surface': '#e5e2e1',
        'on-secondary-container': '#00302a',
        'on-secondary': '#003731',
        'surface-container-highest': '#353534',
        'primary-container': '#fc5929',
        'background': '#131313',
        'error': '#ffb4ab',
        'surface-container': '#201f1f',
        'inverse-primary': '#b02e00',
        'on-secondary-fixed-variant': '#005048',
        'on-primary-container': '#541100',
        'surface-variant': '#353534',
        'surface-container-low': '#1c1b1b',
        'primary-fixed-dim': '#ffb5a0',
        'on-error': '#690005',
        'on-secondary-fixed': '#00201c',
        'on-primary': '#601500',
        'outline-variant': '#5b4139',
        'surface-bright': '#393939',
        'surface': '#131313',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#872100',
        'secondary': '#70d8c8',
        'primary': '#ffb5a0',
        'tertiary-fixed-dim': '#edbbac',
        'on-background': '#e5e2e1',
        'on-surface-variant': '#e4beb4',
        'on-tertiary-container': '#402218',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#8df5e4',
        'tertiary': '#edbbac',
        'on-tertiary': '#47281e',
        'secondary-container': '#32a192',
        'on-tertiary-fixed-variant': '#613e33',
        'surface-tint': '#ffb5a0'
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif']
      }
    },
  },
  plugins: [],
}